### PR TITLE
Add Perl 5.34 to CI tests

### PR DESCRIPTION
**Pull request by ehuelsmann**
# Description

Add Perl 5.34 to the suite of tested Perl versions.

## Type of change

Please delete options that are not relevant.

- [x] Infrastructure

# Checklist:

### CODE REVIEW

**Comment by jonasbn** [comment]
Hi @ehuelsmann 

Does 5.26 hold any significant importance to us or the distribution?

**Comment by ehuelsmann** [comment]
> Does 5.26 hold any significant importance to us or the distribution?

Not as far as I'm able to assess from `perldelta`.

**Review by jonasbn — APPROVED** [review]
LGTM

**Comment by ehuelsmann** [comment]
> lets keep 5.14 (lowest), 5.20, 5.30 and 5.34 (newest)

**Pull request merged**
