### PR TITLE
Dedupe Workflow::Context::init()

### PR DESCRIPTION
**Pull request by ehuelsmann**
# Description

Deduplicate function duplicated by automatic merge.

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

# Checklist:

- [x] I have performed a self-review of my own code
- [x] My changes generate no new warnings
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by jonasbn — APPROVED** [review]
LGTM

**Comment by jonasbn** [comment]
@ehuelsmann can you restore this branch?

**Comment by ehuelsmann** [comment]
@jonasbn This PR/commit does not need backporting to 1.x as there is no duplicate `init()` function there (at the moment).

**Comment by jonasbn** [comment]
Great, marking this as milestone 2.0

**Pull request merged**
