### PR TITLE
Address issue #54 by making get_action() public in Workflow.pm

### PR DESCRIPTION
**Pull request by ehuelsmann**
# Description

By renaming `Workflow->_get_action()` to `get_action()` and documenting
it to be public, consumers of Workflow can retrieve action object
instances and thereby the extra properties registered on them.

This commit introduces a new `_get_action()` method for backward
compatibility with 1.49 and earlier which simply forwards to its
public counterpart.

Fixes/addresses #54

## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)
- [x] This change requires a documentation update

# Checklist:

- [x] My code follows the style guidelines of this project, please see the [contribution guidelines](https://github.com/jonasbn/perl-workflow/blob/master/CONTRIBUTING.md).
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

You might think, that this is one crazy checklist, but it is just as much written for the maintainer of the involved software :-)

### CODE REVIEW

**Comment by ehuelsmann** [comment]
One thing that could make sense with respect to this PR is to deprecate the workflow method `get_action_fields()` as the action object is now accessible directly. However, since the various fields() methods remain documented as "internal", it's probably better to deprecate `get_action_fields()` when those fields are reclassified as "public".

**Comment by ehuelsmann** [comment]
As documented in #54, either the `Workflow->_get_action()` method should become public, or the `Workflow::Factory->get_action()` method should: doing so will enable access to any additional properties passed to the actions when instantiated, including properties which could help generating UIs (such as an `index` field to specify order).

**Review by jonasbn — APPROVED** [review]
Approved

**Comment by jonasbn** [comment]
As for #57 this could be merged onto main/master for inclusion in next release AFAICT

**Comment by ehuelsmann** [comment]
Yes, it can be included in a release without causing issues. It's my conviction that it's the best way to deal with the requirement to "provide access to the fields data for the actions of the current workflow" is best served by making the Action instances available through the workflow. Without these methods, one would need to use the (private) `_factory` accessor to get to the Factory instance and query that for the action objects. Much uglier.

**Pull request merged**
